env:
  ASPNETCORE_ENVIRONMENT: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 🐳 Start Docker containers
        run: docker compose -f docker/docker-compose.yml up -d

      - name: ⏳ Wait for services to be ready
        run: sleep 20

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"