version: '3.9'

services:

  # PostgreSQL - banco principal relacional
  postgres:
    image: postgres:16
    container_name: shopping_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - cache em memória
  redis:
    image: redis:7
    container_name: shopping_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MongoDB - banco NoSQL para leitura/projeção
  mongo:
    image: mongo:7
    container_name: shopping_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Zookeeper - necessário para orquestrar o Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: shopping_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka - mensageria entre os microserviços
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: shopping_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: shopping_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  # Prometheus - coleta de métricas
  prometheus:
    image: prom/prometheus
    container_name: shopping_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka
      - postgres

  # Grafana - visualização de métricas do Prometheus
  grafana:
    image: grafana/grafana
    container_name: shopping_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # Elasticsearch - armazenamento e busca de logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: shopping_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  # Kibana - visualização dos logs via Elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: shopping_kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

# Volumes persistentes com os nomes originais
volumes:
  pg_data:
  mongo_data:
  redis_data:
  kafka_data:
  elastic_data: